### PR TITLE
Add aarch64 CI support

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Yes that's correct. I am testing a Raspberry Pi and I couldn't get xraylib compiling as it only has 1 GB of memory. Fortunately the Azure build machines have 6GB!

**Comment by mrakitin** [comment]
Ah, that'd pretty good! But for running the app, you don't need that much memory, do you?

**Comment by tschoonj** [comment]
No runtime is like only 20 MB.

During the build process, all the datafilee are converted into 1 one huge C source code file (about 1M lines), which takes quite a bit of memory to compile I guess...

**Comment by mrakitin** [comment]
Got it, thanks for the explanation.

A side question: I observed a warning in the logs which I haven't seen before: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=188673&view=logs&j=e9afaa34-1a0f-534e-78fc-fae528ccd915&t=48395e60-bc5f-5e45-7455-d404f0c95f3a&l=1357.
```
...
WARNING: pyldd disagrees with ldd/otool. This will not cause any
WARNING: problems for this build, but please file a bug at:
WARNING: https://github.com/conda/conda-build
WARNING: and (if possible) attach file $PREFIX/lib/python3.8/site-packages/xraylib_np.cpython-38-x86_64-linux-gnu.so
WARNING:
...
```

Does it look familiar? Is it a new feature of conda-build?

**Comment by tschoonj** [comment]
The conda folks must be trying something new...

**Pull request merged**
