### PR TITLE
Disable ruby bindings ; add a license file

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender

**Comment by mrakitin** [comment]
All the builds are passing now. @conda-forge/xraylib, ready for review!

**Comment by mrakitin** [comment]
> Wouldn't it be better to simply explicitly disable the ruby bindings for the macOS build? They are not generated for the Windows and Linux builds so perhaps it would be best to keep things the same on all platforms...

Works for me, as long as the Python package can be imported/used on all 3 platforms 🙂.

> Do you actually use the ruby bindings on macOS?

Not really. Our facility is Linux-based, so we don't heavily use the packages for other platforms, but for the post-analysis users may need the libraries for Windows/OSX.

**Comment by tschoonj** [comment]
In that case, please drop the `ruby` dependency, and add `--disable-ruby` to the `configure` flags in `build.sh`.

Thanks!

**Comment by mrakitin** [comment]
Great solution, thanks @tschoonj! I noticed that it was already disabled for Windows:
https://github.com/conda-forge/xraylib-feedstock/blob/3d765da453b52bb9340a216782256841905b3c74/recipe/bld.bat#L14

**Comment by tschoonj** [comment]
Thanks for your contribution!

**Comment by mrakitin** [comment]
Thank you for your help with this and for accepting the update.

**Pull request merged**
