### PR TITLE
MNT: Try to enable fortran bindings for osx arm.

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

We are trying to build Bmad for osx-arm64. Xraylib is one of the dependencies, and we bumped into the missing bindings.

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by ChristopherMayes** [comment]
Is this able to merge with CircleCI failing?

**Comment by hhslepicka** [comment]
@mrakitin could you help us with a review/merge?

**Review by mrakitin — APPROVED** [review]

**Comment by mrakitin** [comment]
> @mrakitin could you help us with a review/merge?

I am not sure why it appears here, but all relevant packages are built on Azure Pipelines.

**Pull request merged**
